import { Request } from '../types/request';

// Mock available requests for workers to browse
export const mockAvailableRequests: Request[] = [
  {
    id: 'REQ-101',
    serviceType: 'Plumbing',
    title: 'Slow draining kitchen sink',
    description: 'Kitchen sink has been draining slowly. Need a professional to inspect and fix the issue. The problem started about a week ago.',
    location: 'Kitchen',
    street_address: '123 Main St',
    apt: '4B',
    city: 'Boston',
    state: 'MA',
    zip_code: '02101',
    photos: [],
    status: 'waiting_assignment',
    created_at: '2025-12-20T10:00:00Z',
    inspectionFee: 75,
    availabilityWindow: 'Dec 20-22, 2025 (9 AM - 5 PM)',
    locationType: 'Residential',
    petsOnSite: true,
    parkingNotes: 'Street parking available. Visitor parking in front of building.',
    providerName: 'John Doe',
  },
  {
    id: 'REQ-102',
    serviceType: 'HVAC',
    title: 'Annual system maintenance',
    description: 'Need annual HVAC system maintenance and inspection. System is about 5 years old and has been running fine, just need routine checkup.',
    location: 'Basement',
    street_address: '456 Oak Ave',
    city: 'Cambridge',
    state: 'MA',
    zip_code: '02139',
    photos: [],
    status: 'waiting_assignment',
    created_at: '2025-12-21T09:30:00Z',
    inspectionFee: 100,
    availabilityWindow: 'Dec 21-23, 2025 (10 AM - 6 PM)',
    locationType: 'Residential',
    petsOnSite: false,
    parkingNotes: 'Driveway parking available.',
    providerName: 'Sarah Johnson',
  },
  {
    id: 'REQ-103',
    serviceType: 'Electric',
    title: 'Outlets not working',
    description: 'Multiple outlets in the bedroom stopped working. Need electrician to diagnose and repair. No power in 3 outlets on the same wall.',
    location: 'Bedroom',
    street_address: '789 Elm Street',
    apt: '2A',
    city: 'Somerville',
    state: 'MA',
    zip_code: '02144',
    photos: [],
    status: 'waiting_assignment',
    created_at: '2025-12-22T11:15:00Z',
    inspectionFee: 85,
    availabilityWindow: 'Dec 23-24, 2025 (1 PM - 7 PM)',
    locationType: 'Residential',
    petsOnSite: true,
    parkingNotes: 'Street parking only. 2-hour limit.',
    providerName: 'Mike Williams',
  },
  {
    id: 'REQ-104',
    serviceType: 'Carpentry',
    title: 'Cabinet door repair',
    description: 'Kitchen cabinet door hinge is broken and door is hanging loosely. Need carpenter to repair or replace the hinge.',
    location: 'Kitchen',
    street_address: '321 Pine Road',
    city: 'Brookline',
    state: 'MA',
    zip_code: '02445',
    photos: [],
    status: 'waiting_assignment',
    created_at: '2025-12-23T08:45:00Z',
    inspectionFee: 60,
    availabilityWindow: 'Dec 24-26, 2025 (8 AM - 4 PM)',
    locationType: 'Residential',
    petsOnSite: false,
    parkingNotes: 'Garage parking available.',
    providerName: 'Emily Chen',
  },
  {
    id: 'REQ-105',
    serviceType: 'Painting',
    title: 'Living room wall touch-up',
    description: 'Need touch-up painting for living room walls. Some scuffs and marks from moving furniture. About 200 sq ft area.',
    location: 'Living Room',
    street_address: '555 Maple Drive',
    apt: '12',
    city: 'Newton',
    state: 'MA',
    zip_code: '02458',
    photos: [],
    status: 'waiting_assignment',
    created_at: '2025-12-24T14:20:00Z',
    inspectionFee: 50,
    availabilityWindow: 'Dec 26-28, 2025 (10 AM - 3 PM)',
    locationType: 'Residential',
    petsOnSite: true,
    parkingNotes: 'Street parking available.',
    providerName: 'David Martinez',
  },
  {
    id: 'REQ-106',
    serviceType: 'Plumbing',
    title: 'Leaky bathroom faucet',
    description: 'Bathroom sink faucet has a slow leak. Drips constantly even when turned off tight. Wasting water and need it fixed soon.',
    location: 'Bathroom',
    street_address: '888 Cedar Lane',
    city: 'Watertown',
    state: 'MA',
    zip_code: '02472',
    photos: [],
    status: 'waiting_assignment',
    created_at: '2025-12-25T09:00:00Z',
    inspectionFee: 70,
    availabilityWindow: 'Dec 27-29, 2025 (9 AM - 5 PM)',
    locationType: 'Residential',
    petsOnSite: false,
    parkingNotes: 'Driveway and street parking available.',
    providerName: 'Lisa Anderson',
  },
];

// Helper function to calculate distance (mock for now)
export const calculateDistance = (requestId: string): number => {
  const distances: Record<string, number> = {
    'REQ-101': 2.3,
    'REQ-102': 4.7,
    'REQ-103': 1.2,
    'REQ-104': 3.5,
    'REQ-105': 6.1,
    'REQ-106': 2.8,
  };
  return distances[requestId] || 5.0;
};

// Helper function to get client rating (mock for now)
export const getClientRating = (requestId: string): number => {
  const ratings: Record<string, number> = {
    'REQ-101': 4.8,
    'REQ-102': 5.0,
    'REQ-103': 4.5,
    'REQ-104': 4.9,
    'REQ-105': 4.7,
    'REQ-106': 4.6,
  };
  return ratings[requestId] || 4.5;
};
